import { useEffect, useRef, type ReactNode } from 'react';
import type { Schema } from '../api/types';
export const number = (n: number) => new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(n);
export function metric(value:Schema['NumericReading']|undefined,percent=false):string {return !value?'Нет данных':value.status==='available'?(percent?String(Math.round(value.value*100)):number(value.value))+(percent?'%':''):`Недоступно (${value.reason})`;}
export function Popup({children,label,onClose,className=''}:{children:ReactNode;label:string;onClose:()=>void;className?:string}) {
 const shell=className.includes('popup-time')?'50000.svg':className.includes('popup-calendar')?'calendar-wide.svg':className.includes('popup-routes')?'fe310.svg':className.includes('popup-fleet')?'aec07.svg':undefined;
 const ref=useRef<HTMLDivElement>(null);const close=useRef(onClose);close.current=onClose;
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.querySelector<HTMLElement>('[role=slider],button:not(.popup-close),input,select')?.focus({preventScroll:true});if(ref.current)ref.current.scrollTop=0;const outside=(e:PointerEvent)=>{if(!ref.current?.contains(e.target as Node)&&!(e.target as HTMLElement).closest('[data-popup-trigger]'))close.current();};document.addEventListener('pointerdown',outside);return()=>{document.removeEventListener('pointerdown',outside);previous?.focus({preventScroll:true});};},[]);
 return <div ref={ref} role="dialog" inert={className.includes('popup-leaving')} aria-label={label} className={`popup ${className}`} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();onClose();}if(e.key==='Tab'){const nodes=Array.from(ref.current!.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),[tabindex="0"]'));if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus({preventScroll:true});}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus({preventScroll:true});}}}}><button className="popup-close sr-only" onClick={onClose}>Закрыть</button>{shell&&<><div className="popup-glass" aria-hidden="true"/><img className="popup-shell" src={`/assets/icons/${shell}`} alt=""/></>}{children}</div>;
}
export function Icon({name,alt=''}:{name:string;alt?:string}){return <img className="asset-icon" src={'/assets/icons/'+name} alt={alt}/>;}
